# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

before_install:
  - tlmgr install graphicx amsmath amssymb amsfonts setspace enumitem hyperref biber

os:
  - linux
  - osx

r:
  - release
  - devel
  
cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com
  
r_packages:
  - covr

sudo: false

# disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
