# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

#before_install:
#  - tlmgr install amsmath amsfonts setspace enumitem hyperref biblatex
# disable_homebrew: true

os:
  - linux
  - osx

r:
  - release
  - devel  

r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes --no-examples'
 
cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com
  
r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
