# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - tlmgr install latex-xcolor texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra texlive-extra-utils texlive-latex-recommended texlive-latex-extra
  
os:
  - linux
  - osx

r:
  - release
  - devel
  
cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com
  
r_packages:
  - covr

sudo: false

# disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
